/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]

#[repr(C)] #[derive(Copy, Clone, Debug)] pub struct foo { bar: ::std::os::raw::c_int, }

/**
 * bar should compile. It will normally derive default, but our blacklist of foo
 * and replacement for another type that doesn't implement it would prevent it
 * from building if --no-derive-default didn't work.
 */
#[repr(C)]
#[derive(Debug, Copy)]
pub struct bar {
    pub foo: foo,
    pub baz: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_bar() {
    assert_eq!(::std::mem::size_of::<bar>() , 8usize);
    assert_eq!(::std::mem::align_of::<bar>() , 4usize);
}
impl Clone for bar {
    fn clone(&self) -> Self { *self }
}
